Repository fidel-bello/epic-poggers-ecomstore, pull requests merged in 2022-05, with the labels that each got.

#68 added protectroute api for authenticated routes. this way no one can…
  Backend/src/app/controllers/authControllers.ts
  Backend/src/app/routes/productRoutes.ts
  Frontend/package-lock.json
Labels: bug, enhancement

#78 feat: show products on home page
  Frontend/README.md
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/pages/Home.tsx
  Frontend/src/types.ts
Labels: enhancement

#76 fix(backend): add cross env capability & notreload
  Backend/package-lock.json
  Backend/package.json
Labels: bug, enhancement

#87 fix: pagination page count
  Frontend/src/pages/Home.tsx
Labels: bug

#88 added spinner gif
  Frontend/src/App.tsx
  Frontend/src/assets/images/spinner.gif
Labels: documentation

#102 feature: added an update password for users
  Backend/src/app/controllers/authControllers.ts
  Backend/src/app/routes/authRoutes.ts
Labels: enhancement

#107 testing user model with a create order
  Backend/src/app/controllers/orderControllers.ts
  Backend/src/app/routes/index.ts
  Backend/src/app/routes/orderRoutes.ts
Labels: enhancement
